### ISSUE TITLE
Comma inside String error

### ISSUE THREAD

**Issue by terciogarcia** [pradeep-mishra/csvjson#11]
I'm using csvjson in a React project.
When i try to use toColumnArray function with a CSV with a comma inside a string (eg "foo,bar"), i get the following error:
`index.js:34 Uncaught TypeError: Cannot read property 'push' of undefined`.
It seems the algorythim identifies comma as CSV separator instead part of the string

**Comment by tulsirampalavalasa** [comment]
Hi  i am also facing the same issue

**Comment by pradeep-mishra** [comment]
Hi ,
Sorry for delayed response
this feature is added now, please refer doc

**Comment by damianobarbati** [comment]
how to solve this?
