### ISSUE TITLE
Double quotes in CSV cause error

### ISSUE THREAD

**Issue by benkamin** [pradeep-mishra/csvjson#12]
When parsing CSV, escaped double quotes cause error. 
`TypeError: Cannot read property '0' of null
    at node_modules/csvjson/index.js:74:55
    at Array.forEach (native)
    at node_modules/csvjson/index.js:73:21
    at Array.forEach (native)
    at Object.toObject (node_modules/csvjson/index.js:67:13)`

Double quotes in CSV are escaped with double quotes, so it looks looks like this:
"this string contains ""double quotes"""
But using toObject to parse CSV files which includes such escaped quotes seems to invoke this error.

**Comment by pradeep-mishra** [comment]
try like this

var result = csvjson.toObject(data, { quote : true });
