### ISSUE TITLE
TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by aikomastboom** [pradeep-mishra/csvjson#14]
version 4.1.2

```
var data = "
A;B;C\n
;\n
"
csvjson.toObject(data, {delimiter:';'})
```

result:
```
TypeError: Cannot read property 'trim' of undefined
       at _trimQuote (./node_modules/csvjson/index.js:397:15)
```

expected:
not sure... 
- throw your own descriptive parse exception?
- add callback / promise interface to pass back errors nicely?

**Comment by BenJMcDonald** [comment]
Work around: add if(str) before the return, and else return "" after

**Comment by pradeep-mishra** [comment]
fixed, added BenJMcDonald fix, and pushed it to npm
