### ISSUE TITLE
Partial Header if '-' in key when converting JSON > CSV

### ISSUE THREAD

**Issue by kylegracey** [pradeep-mishra/csvjson#18]
When I'm converting JSON to CSV using the options:
`var options = {
    headers   : "key",
    delimiter   : ";"
}`

One of the keys in my object is "Asset Sub-Type". The full CSV is rendered fine, but the header for the field associated with "Asset Sub-Type" is renamed to just "Type".

**Comment by pradeep-mishra** [comment]
fixed.
