### ISSUE TITLE
Support schema object generation of arrays of a objects

### ISSUE THREAD

**Issue by robinhowlett** [pradeep-mishra/csvjson#5]
For example, it would be great to have

id,title,contents[].name,contents[].title,contents[].type

{"id": "XXX", "title": "YYY", "contents": [ { "name": "AAA", "title": "BBB", "type": "CCC"} ]

Similarly, something like "contents[1].title" and "contents[2].title" could be used for multiple objects within an array

**Comment by ralucas** [comment]
See PR #8
